import type { VenueInsert } from "./types";

/**
 * Converts a venue name to a URL-safe slug.
 * Exported for use when adding venues programmatically in the future.
 */
export function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[àáâãäåæ]/g, "a")
    .replace(/[çć]/g, "c")
    .replace(/[èéêë]/g, "e")
    .replace(/[ìíîï]/g, "i")
    .replace(/[òóôõöø]/g, "o")
    .replace(/[ùúûü]/g, "u")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-|-$/g, "");
}

export const SEED_VENUES: VenueInsert[] = [
  // ──────────────────────────────────────────
  // DANCE CLUBS
  // ──────────────────────────────────────────
  {
    name: "Zouk",
    slug: "zouk",
    category: "Dance Club",
    neighbourhood: "Clarke Quay",
    address: "3C River Valley Road, #01-05 to #02-06 The Cannery, S(179022)",
    phone: "+65 9006 8549",
    website: "https://zoukgroup.com/singapore",
    booking_url: "https://zoukgroup.com/singapore/singapore/events",
    hours: "Wed–Sat, 10pm till late",
    description:
      "Singapore's most iconic multi-room club — Zouk main room, Capital and Phuture under one roof. International house, EDM and techno weekly, plus the legendary Mambo Jambo retro night.",
    signature_drinks: null,
    entertainment: "International house, EDM and techno; Mambo Jambo retro night",
    known_promotions: null,
    instagram: "@zouksingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Marquee",
    slug: "marquee",
    category: "Dance Club",
    neighbourhood: "Marina Bay Sands",
    address: "10 Bayfront Avenue, #B1-67 The Shoppes at Marina Bay Sands, S(018956)",
    phone: null,
    website: "https://taogroup.com/venues/marquee-singapore",
    booking_url: null,
    hours: "Fri & Sat + eve of PH, 10pm–6am",
    description:
      "Singapore's largest nightclub with 60+ international acts per year. Four themed bars, a ferris wheel, three-storey slide and legendary F1 Grand Prix parties.",
    signature_drinks: null,
    entertainment: "60+ international DJ acts per year; ferris wheel and three-storey slide; F1 Grand Prix parties",
    known_promotions: null,
    instagram: "@marqueesingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "AVENUE Singapore",
    slug: "avenue-singapore",
    category: "Dance Club",
    neighbourhood: "Marina Bay Sands",
    address: "2 Bayfront Avenue, B1 The Shoppes at Marina Bay Sands",
    phone: null,
    website: "https://taogroup.com",
    booking_url: null,
    hours: "Typically Wed–Sat, late",
    description:
      "New York penthouse concept — hip-hop and sing-along DJ sets, bowling alley, pool table, craft cocktails. The after-party favourite.",
    signature_drinks: null,
    entertainment: "Hip-hop and sing-along DJ sets; bowling alley; pool table",
    known_promotions: null,
    instagram: "@avenuesingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "CÉ LA VI Club Lounge",
    slug: "ce-la-vi-club-lounge",
    category: "Dance Club",
    neighbourhood: "Marina Bay Sands",
    address: "1 Bayfront Avenue, Tower 3 SkyPark L57",
    phone: null,
    website: "https://celavi.com",
    booking_url: null,
    hours: "Club nights Wed–Sat",
    description:
      "Rooftop club lounge 57 floors above the city. Electronic, hip-hop and R&B DJ sets with Singapore's most spectacular skyline as backdrop.",
    signature_drinks: null,
    entertainment: "Electronic, hip-hop and R&B DJ sets",
    known_promotions: "~S$35 walk-in entry incl. a drink; waived with reservation",
    instagram: "@celavisingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Yang Club",
    slug: "yang-club",
    category: "Dance Club",
    neighbourhood: "Clarke Quay",
    address: "3A River Valley Road, #01-02 The Riverhouse",
    phone: null,
    website: null,
    booking_url: null,
    hours: "Typically Wed–Sat",
    description:
      "Hip-hop, electro pop, K-pop and Top 40 in a 150-year-old Chinese mansion. Live band sets.",
    signature_drinks: null,
    entertainment: "Hip-hop, electro pop, K-pop and Top 40 DJ sets; live band",
    known_promotions: null,
    instagram: "@yangclubsingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Headquarters (Club HQ)",
    slug: "headquarters-club-hq",
    category: "Dance Club",
    neighbourhood: "Boat Quay",
    address: "66A Boat Quay",
    phone: null,
    website: null,
    booking_url: null,
    hours: "Typically Fri–Sat, late",
    description:
      "Underground techno and house institution. Local and regional DJ bookings. Music-first.",
    signature_drinks: null,
    entertainment: "Underground techno and house; local and regional DJ bookings",
    known_promotions: null,
    instagram: "@hqsingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "TUFF CLUB",
    slug: "tuff-club",
    category: "Dance Club",
    neighbourhood: "CBD",
    address: "138 Robinson Road, Oxley Tower",
    phone: null,
    website: null,
    booking_url: null,
    hours: "Event-driven; check Resident Advisor",
    description:
      "Electronic music venue with serious international bookings — Rey&Kjavik, CARAVEL, Dax J. Minimal, music-first. Tickets via Resident Advisor.",
    signature_drinks: null,
    entertainment: "Electronic music; international DJ bookings (Resident Advisor)",
    known_promotions: null,
    instagram: "@tuffclubsg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Cherry Discotheque",
    slug: "cherry-discotheque",
    category: "Dance Club",
    neighbourhood: "CBD",
    address: null,
    phone: null,
    website: null,
    booking_url: null,
    hours: "Fri–Sat, late",
    description:
      "Hip-hop parties and local DJ collective energy. Cosy bar-club hybrid with a loyal following.",
    signature_drinks: null,
    entertainment: "Hip-hop parties; local DJ collective",
    known_promotions: null,
    instagram: "@cherrydisco",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },

  // ──────────────────────────────────────────
  // COCKTAIL BARS
  // ──────────────────────────────────────────
  {
    name: "Jigger & Pony",
    slug: "jigger-and-pony",
    category: "Cocktail Bar",
    neighbourhood: "Tanjong Pagar",
    address: "165 Tanjong Pagar Road, Amara Singapore lobby",
    phone: null,
    website: "https://jiggerandpony.com",
    booking_url: null,
    hours: "Daily, evening service",
    description:
      "No.3 Asia's 50 Best Bars and No.9 in the world. Tatler Bar of the Year 2026. The Smash menuzine defines Singapore's cocktail scene.",
    signature_drinks: "Champagne Ramos Fizz, Lycheetini, Espresso Martini",
    entertainment: null,
    known_promotions: "Cocktails from ~S$28++; book ahead",
    instagram: "@jiggerandponysg",
    google_place_id: null,
    photo_url: null,
    is_featured: true,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Atlas",
    slug: "atlas",
    category: "Cocktail Bar",
    neighbourhood: "Bugis",
    address: "600 North Bridge Road, Parkview Square, S(188778)",
    phone: null,
    website: "https://atlasbar.sg",
    booking_url: null,
    hours: "Typically Mon–Sat, evenings",
    description:
      "Art-deco grandeur, a 15-metre gin tower, Singapore's largest gin collection. Atlas Martini with champagne vinegar. Occasional live jazz nights.",
    signature_drinks: "Atlas Martini with champagne vinegar",
    entertainment: "Occasional live jazz nights",
    known_promotions: "Cocktails from S$25",
    instagram: "@atlasbarsg",
    google_place_id: null,
    photo_url: null,
    is_featured: true,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Manhattan",
    slug: "manhattan",
    category: "Cocktail Bar",
    neighbourhood: "Orchard",
    address: "1 Cuscaden Road, Level 2, Conrad Singapore Orchard, S(249715)",
    phone: null,
    website: null,
    booking_url: null,
    hours: "Typically Tue–Sun evenings",
    description:
      "Consistently on World's and Asia's 50 Best lists. Barrel-aged cocktails and famed brunch inside the Conrad Singapore Orchard.",
    signature_drinks: null,
    entertainment: null,
    known_promotions: null,
    instagram: "@manhattan_sg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Native",
    slug: "native",
    category: "Cocktail Bar",
    neighbourhood: "Amoy Street",
    address: "52A Amoy Street",
    phone: null,
    website: "https://tribenative.com",
    booking_url: null,
    hours: "Mon–Sat evenings",
    description:
      "Asia's 50 Best regular. Indigenous Southeast Asian ingredients, foraged spirits, regional produce. One of Singapore's most thoughtful cocktail menus.",
    signature_drinks: null,
    entertainment: null,
    known_promotions: null,
    instagram: "@nativebarsg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Cat Bite Club",
    slug: "cat-bite-club",
    category: "Cocktail Bar",
    neighbourhood: "Duxton",
    address: "75 Duxton Road",
    phone: null,
    website: "https://catbiteclub.com",
    booking_url: null,
    hours: "Tue–Sat evenings",
    description:
      "No.44 Asia's 50 Best 2025 and Tatler Bar of the Year 2025. Agave and rice spirits — mezcal, tequila, sotol, baijiu, shochu.",
    signature_drinks: "Spirits Explorer Passport — mezcal, tequila, sotol, baijiu, shochu",
    entertainment: null,
    known_promotions: null,
    instagram: "@catbiteclub",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Nutmeg & Clove",
    slug: "nutmeg-and-clove",
    category: "Cocktail Bar",
    neighbourhood: "Bras Basah",
    address: "8 Purvis Street",
    phone: null,
    website: "https://nutmegclove.com",
    booking_url: null,
    hours: "Mon–Sat evenings",
    description:
      "No.24 Asia's 50 Best 2025. Singapore-pantry cocktails — nutmeg, clove, gula melaka, pandan, calamansi, laksa leaf.",
    signature_drinks: "The Coffee Negroni; Singapore-pantry cocktails with nutmeg, clove, gula melaka, pandan",
    entertainment: null,
    known_promotions: null,
    instagram: "@nutmegclove",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Offtrack",
    slug: "offtrack",
    category: "Cocktail Bar",
    neighbourhood: "Boat Quay",
    address: "24 North Canal Road",
    phone: null,
    website: "https://offtrack.sg",
    booking_url: null,
    hours: "Tue–Sat, till late",
    description:
      "No.23 Asia's 50 Best 2025. Custom hi-fi listening system, fermented house ingredients. Strongest bar-level DJ programming in the city — Darker Than Wax and Ice Cream Sundays rosters.",
    signature_drinks: null,
    entertainment: "Hi-fi listening bar; Darker Than Wax and Ice Cream Sundays DJ rosters",
    known_promotions: null,
    instagram: "@offtrack.sg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Live Twice",
    slug: "live-twice",
    category: "Cocktail Bar",
    neighbourhood: "Bukit Pasoh",
    address: "18/20 Bukit Pasoh Road",
    phone: null,
    website: "https://livetwice.sg",
    booking_url: null,
    hours: "Mon–Sat evenings",
    description:
      "Japanese spirits and bartending culture. 1960s-Tokyo room with jazz on vinyl. Tatler Best 20 Bars 2026.",
    signature_drinks: "The Little Crane",
    entertainment: "Jazz on vinyl",
    known_promotions: null,
    instagram: "@livetwicebar",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Gibson",
    slug: "gibson",
    category: "Cocktail Bar",
    neighbourhood: "Bukit Pasoh",
    address: "20 Bukit Pasoh Road, Level 2",
    phone: null,
    website: "https://gibsonbar.sg",
    booking_url: null,
    hours: "Mon–Sat evenings",
    description:
      "10th anniversary year. The Gibson cocktail — Roku gin, house ginjo sake-vermouth, house-cured garnishes — is a benchmark. Vintage heritage-shophouse room.",
    signature_drinks: "The Gibson — Roku gin, house ginjo sake-vermouth, house-cured garnishes",
    entertainment: null,
    known_promotions: null,
    instagram: "@gibsonbarsg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Sago House",
    slug: "sago-house",
    category: "Cocktail Bar",
    neighbourhood: "Chinatown",
    address: "40B Sago Street",
    phone: null,
    website: "https://sagohouse.sg",
    booking_url: null,
    hours: "Wed–Sun evenings",
    description:
      "DIY speakeasy ethic, weekly-changing scratch menu from market produce. Asia's 50 Best regular. Small room — book well ahead.",
    signature_drinks: null,
    entertainment: null,
    known_promotions: "Book well ahead — small room",
    instagram: "@sagohousesg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Employees Only",
    slug: "employees-only",
    category: "Cocktail Bar",
    neighbourhood: "Amoy Street",
    address: "112 Amoy Street",
    phone: null,
    website: "https://employeesonlysg.com",
    booking_url: null,
    hours: "Daily, till late",
    description:
      "10th anniversary in Singapore for the iconic New York import. White-coat bartenders, NY classic cocktails, late-night kitchen.",
    signature_drinks: null,
    entertainment: "Late-night kitchen",
    known_promotions: null,
    instagram: "@employeesonlysg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Stay Gold Flamingo",
    slug: "stay-gold-flamingo",
    category: "Cocktail Bar",
    neighbourhood: "Amoy Street",
    address: "69 Amoy Street",
    phone: null,
    website: null,
    booking_url: null,
    hours: "Mon–Sat, till late",
    description:
      "Café by day, serious cocktail bar by night. The Bartender's Diary menu, no-gimmick classics.",
    signature_drinks: null,
    entertainment: null,
    known_promotions: null,
    instagram: "@staygoldflamingo",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "The Elephant Room",
    slug: "the-elephant-room",
    category: "Cocktail Bar",
    neighbourhood: "Tanjong Pagar",
    address: "33 Tanjong Pagar Road, #01-02, S(088456)",
    phone: null,
    website: "https://elephantroom.sg",
    booking_url: null,
    hours: "Sun–Thu 6pm–1am; Fri–Sat 6pm–2am",
    description:
      "Little India-inspired cocktails. The Buffalo Road and crab rasam riffs are unlike anything else in Singapore. Refreshed 2026 menu.",
    signature_drinks: "The Buffalo Road; crab rasam riff cocktails",
    entertainment: null,
    known_promotions: "Cocktails from S$25",
    instagram: "@elephantroom.sg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "BOP (Bartenders of Pony)",
    slug: "bop-bartenders-of-pony",
    category: "Cocktail Bar",
    neighbourhood: "Tanjong Pagar",
    address: null,
    phone: null,
    website: "https://jiggerandpony.com",
    booking_url: null,
    hours: "Opened early 2026",
    description:
      "Jigger & Pony Group's Korean drinking culture concept. Bokbunja POP tableside, BOP Martini, somaek with soju snow, fried chicken and gimbap.",
    signature_drinks: "Bokbunja POP tableside, BOP Martini, somaek with soju snow",
    entertainment: null,
    known_promotions: null,
    instagram: "@jiggerandponysg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "MOGA",
    slug: "moga",
    category: "Cocktail Bar",
    neighbourhood: "City Hall",
    address: "1 Hill Street, Pullman Singapore Hill Street, S(179949)",
    phone: "+65 6019 7888",
    website: null,
    booking_url: null,
    hours: "Mon–Thu 12pm–3pm & 6pm–12am; Fri–Sat 12pm–3pm & 6pm–1am; closed Sun",
    description:
      "Japanese listening-bar sensibility. Japan-only spirits — sake, wine, craft whisky. Seasonal whisky tasting journeys.",
    signature_drinks: "Seasonal whisky tasting journeys; Japan-only sake, wine and craft whisky",
    entertainment: "Listening-bar format; seasonal whisky journeys",
    known_promotions: null,
    instagram: "@moga.sg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Pop City X Pony",
    slug: "pop-city-x-pony",
    category: "Cocktail Bar",
    neighbourhood: "CBD",
    address: null,
    phone: null,
    website: "https://jiggerandpony.com",
    booking_url: null,
    hours: "Opened Dec 2025",
    description:
      "Japanese city-pop concept with House of Suntory. Pop City Sour, Bar Mixtape private nook, DJ and listening-room programming.",
    signature_drinks: "Pop City Sour",
    entertainment: "DJ and listening-room programming; Bar Mixtape private nook",
    known_promotions: null,
    instagram: "@jiggerandponysg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Bar Bon Funk",
    slug: "bar-bon-funk",
    category: "Cocktail Bar",
    neighbourhood: "Club Street",
    address: null,
    phone: null,
    website: "https://lobehold.com",
    booking_url: null,
    hours: "Rotating DJ nights Wed & Sat",
    description:
      "Lo & Behold Group's fermentation-led vinyl living room. Pizza-infused Bloody Mary, sonic-aged Negroni.",
    signature_drinks: "Pizza-infused Bloody Mary, sonic-aged Negroni",
    entertainment: "Vinyl DJ nights Wednesday and Saturday",
    known_promotions: null,
    instagram: "@barbonfunk",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Bae's Cocktail Club",
    slug: "baes-cocktail-club",
    category: "Cocktail Bar",
    neighbourhood: "CBD",
    address: null,
    phone: null,
    website: null,
    booking_url: null,
    hours: "Bar till ~11pm; club after",
    description:
      "Korean-flair cocktails that flip into a 90s throwback dance floor after 11pm.",
    signature_drinks: null,
    entertainment: "Korean-flair cocktails; 90s throwback dance floor after 11pm",
    known_promotions: null,
    instagram: "@baescocktailclub",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },

  // ──────────────────────────────────────────
  // ROOFTOP BARS
  // ──────────────────────────────────────────
  {
    name: "Lantern",
    slug: "lantern",
    category: "Rooftop Bar",
    neighbourhood: "Marina Bay",
    address: "80 Collyer Quay, Rooftop L6, The Fullerton Bay Hotel, S(049326)",
    phone: null,
    website: "https://fullertonhotels.com",
    booking_url: null,
    hours: "Sun–Thu 5pm–12am (LO 11.15pm); Fri, Sat & eve of PH 5pm–1am",
    description:
      "Poolside rooftop terrace at the Fullerton Bay Hotel. Live music and DJ sets Wed–Sat. Fullerton Sling and Sydney Sling.",
    signature_drinks: "Fullerton Sling, Sydney Sling",
    entertainment: "Live music and DJ sets Wed–Sat",
    known_promotions: "Drinks from ~S$14",
    instagram: "@fullertonbayhotel",
    google_place_id: null,
    photo_url: null,
    is_featured: true,
    is_verified: true,
    is_active: true,
  },
  {
    name: "CÉ LA VI SkyBar",
    slug: "ce-la-vi-skybar",
    category: "Rooftop Bar",
    neighbourhood: "Marina Bay Sands",
    address: "1 Bayfront Avenue, SkyPark Tower 3 L57",
    phone: null,
    website: "https://celavi.com",
    booking_url: null,
    hours: "Daily",
    description:
      "57th floor panoramic skyline views. DJ sets nightly into club lounge. Sunset golden hour is peak.",
    signature_drinks: null,
    entertainment: "DJ sets nightly",
    known_promotions: "~S$35 walk-in entry, waived with booking",
    instagram: "@celavisingapore",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
  {
    name: "Smoke & Mirrors",
    slug: "smoke-and-mirrors",
    category: "Rooftop Bar",
    neighbourhood: "City Hall",
    address: "1 St Andrew's Road, #06-01 National Gallery Singapore",
    phone: null,
    website: "https://smokeandmirrors.com.sg",
    booking_url: null,
    hours: "Mon–Fri 12pm–3pm, 6pm–11pm; Sat 6pm–11pm",
    description:
      "Time Out world No.2 rooftop bar atop National Gallery Singapore. Asia's 50 Best regular. Padang-to-Marina-Bay panorama.",
    signature_drinks: "Green Gimlet, Pass the Pineapple, Peking-duck daiquiri",
    entertainment: null,
    known_promotions: null,
    instagram: "@smokeandmirrorsbarsg",
    google_place_id: null,
    photo_url: null,
    is_featured: true,
    is_verified: true,
    is_active: true,
  },

  // ──────────────────────────────────────────
  // PUB / BREWERY
  // ──────────────────────────────────────────
  {
    name: "LeVeL33",
    slug: "level33",
    category: "Pub / Brewery",
    neighbourhood: "Marina Bay",
    address: "8 Marina Boulevard, #33-01 Marina Bay Financial Centre Tower 1",
    phone: "+65 6834 3133",
    website: "https://level33.com.sg",
    booking_url: null,
    hours: "Daily incl. PH, 12pm–11pm",
    description:
      "World's highest urban craft microbrewery. House lager, IPA, wheat and porter brewed on-site. Happy-hour pricing before 8pm.",
    signature_drinks: "House lager, IPA, wheat beer and porter brewed on-site",
    entertainment: "Friday brewery tours at 3pm",
    known_promotions: "Friday brewery tours S$58 pp; happy-hour pricing before 8pm",
    instagram: "@level33sg",
    google_place_id: null,
    photo_url: null,
    is_featured: false,
    is_verified: true,
    is_active: true,
  },
];
